site_name: ACCESS Community Documentation

# Git repository
repo_url: https://github.com/ACCESS-Hive/access_docs
repo_name: ACCESS-Community-Docs
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  logo: assets/ACCESSLogoJustPlanet.png

# Footer

extra:
  generator: false

copyright: Copyright &copy; 2023 - ACCESS-NRI

extra_css:
  - css/fontello.css

plugins: 
      
# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences


# Navigation
nav:
  - Welcome:
    - index.md
    - License: LICENSE.md
  - ACCESS-CM2: 
    - access_cm2/index.md
    - Getting Started: access_cm2/getting-started.md
    - Rose, Cylc and Rosie: access_cm2/rose-cylc-rosie.md
    - Experiments: access_cm2/experiments.md
  - ACCESS-ESM1.5: 
      - access_esm1_5/index.md
  - ACCESS-OM2:
      - access_om2/index.md
  - ACCESS models:
      - access_models/index.md
      - Model Configurations:
        - access_models/model-configs/index.md
        - Model Specifications: access_models/model-configs/access-model-specs.md
      - Getting Started: access_models/getting-started.md
      - Tutorials:
        - access_models/tutorials/index.md
        - Running a Standard Suite: access_models/tutorials/run-suite-tut.md
        - Running a Regional Suite: access_models/tutorials/regional-suite-tut.md
        - Running a Climate Suite: access_models/tutorials/climate-suite-tut.md
      - How-to Guides:
        - access_models/how-to/index.md
        - Change Time Frame: access_models/how-to/how-to-change-time-frame.md
        - Add New Diagnostics: access_models/how-to/how-to-add-new-diagnostics.md
        - Modify Ancillary Files: access_models/how-to/how-to-modify-ancillary-files.md
        - Troubleshooting: access_models/how-to/how-to-troubleshoot.md
      - UM and UM-Related:
        - access_models/references/index.md
        - UM Documentation: access_models/references/um-documentation.md
        - Scientific Tools: access_models/references/scitools.md
        - Rose, Cylc, Rosie: access_models/references/rose-cylc-doc.md
      - ACCESS Technical Details:
        - access_models/access-tech-info/index.md
        - Ancillary Files: access_models/access-tech-info/ancillary-files.md
        - Scientific References: access_models/access-tech-info/sci-references.md
        - Climate Suite Structure: access_models/access-tech-info/climate-suite-structure.md
        - Model Input and Forcing: access_models/access-tech-info/model-input-and-forcing.md
        - Installing new UM and JULES releases: access_models/access-tech-info/install-um-release.md
        - UM and JULES rose-stem testing: access_models/access-tech-info/rose-stem.md
      - UM Partnership Resources:
        - access_models/um-partner-resources/index.md
        - RMED: access_models/um-partner-resources/rmed.md
        - GMED: access_models/um-partner-resources/gmed.md
        - LFRic: access_models/um-partner-resources/lfric.md
      - Glossary: 
        - access_models/glossary/index.md

