site_name: ACCESS Community Documentation

# Git repository
repo_url: https://github.com/ACCESS-Hive/access_docs
repo_name: ACCESS-Community-Docs
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/

# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  logo: assets/ACCESSLogoJustPlanet.png

# Footer

extra:
  generator: false

copyright: Copyright &copy; 2023 - ACCESS-NRI

extra_css:
  - css/fontello.css

# Extensions
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences


# Navigation
nav:
  - Welcome:
    - index.md
    - License: LICENSE.md
  - UM and UM related:
      - um/index.md
      - Getting Started: um/getting-started.md
      - UM Partnership Resources:
        - um/um-partner-resources/index.md
        - RMED: um/um-partner-resources/rmed.md
        - GMED: um/um-partner-resources/gmed.md
        - LFRic: um/um-partner-resources/lfric.md
      - Tutorials:
        - um/tutorials/index.md
        - Running a Standard Suite: um/tutorials/run-suite-tut.md
        - Running a Regional Suite : um/tutorials/regional-suite-tut.md
        - Running a Climate Suite: um/tutorials/climate-suite-tut.md
      - How-to Guides:
        - um/how-to/index.md
        - Change Time Frame: um/how-to/how-to-change-time-frame.md
        - Add New Diagnostics: um/how-to/how-to-add-new-diagnostics.md
        - Modify Ancillary Files: um/how-to/how-to-modify-ancillary-files.md
        - Troubleshooting: um/how-to/how-to-troubleshoot.md
      - References:
        - um/references/index.md
        - UM Documentation: um/references/um-documentation.md
        - Scientific Tools: um/references/scitools.md
        - Rose, Cylc, Rosie: um/references/rose-cylc-doc.md
      - ACCESS Technical Details:
        - um/access-tech-info/index.md
        - ACCESS Model Configurations: um/access-tech-info/access-configs.md
        - Ancillary Files: um/access-tech-info/ancillary-files.md
        - Scientific References: um/access-tech-info/sci-references.md
        - ACCESS Climate Suite Structure: um/access-tech-info/access-climate-suite-structure.md
        - Model Input and Forcing: um/access-tech-info/model-input-and-forcing.md
        - Installing new UM and JULES releases: um/access-tech-info/install-um-release.md
        - UM and JULES rose-stem testing: um/access-tech-info/rose-stem.md
      - Glossary: 
        - um/glossary/index.md
