site_name: ACCESS Community Documentation

# Git repository
repo_url: https://github.com/ACCESS-Hive/access_docs
repo_name: ACCESS-Community-Docs
# Material default to a "master" branch, need to change to "main"
edit_uri: edit/main/docs/


# Theme
theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: light
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: brown
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  logo: assets/ACCESSLogoJustPlanet.png

# Footer

extra:
  generator: false

copyright: Copyright &copy; 2023 - ACCESS-NRI

extra_css:
  - css/fontello.css

# Extensions
markdown_extensions: 
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences

  
# Navigation
nav:
  - Welcome: 
    - index.md
    - License: LICENSE.md
  - UM and UM related:
      - um/index.md
      - Getting Started: um/getting_started.md
      - Learning Orientated Tutorials: um/tutorials/index.md
      - Goal Orientated How-To Guides: um/how-to/index.md
      - Information Orientated References: um/reference/index.md
      - Learning Orientated Discussion: um/discussion/index.md
